sudo: required
services:
  - docker
language: node_js
notifications:
  email: false
node_js:
  - 6
before_script:
  - mkdir -p test/.minio
  - docker-compose up -d
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
env:
  global:
    - S3_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
    - S3_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    - S3_ENDPOINT=http://127.0.0.1:9000